name:                aoc2018
version:             0.1.0.0
github:              "mstksg/advent-of-code-2018"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            "Advent of Code 2018 solutions and auto-runner"
category:            Web

description: |
    It's the Advent of Code 2018!

    This package contains Advent of 2018 solutions (spoilers!) and
    auto-runner.  Each challenge exists in its own module, and module headers
    will also include a brief synopsis and reflection.

ghc-options:
- -Wall
- -Wcompat
- -Wno-partial-type-signatures
- -Wredundant-constraints

default-extensions:
- ApplicativeDo
- BangPatterns
- BlockArguments
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MonoLocalBinds
- MultiWayIf
- NumDecimals
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeInType
- TypeOperators
- ViewPatterns


dependencies:
- base >= 4.7 && < 5
- containers
- finite-typelits
- lens
- mtl
- ansi-terminal

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - criterion
  - curl
  - data-default
  - deepseq
  - directory
  - filepath
  - haskeline
  - haskell-names
  - haskell-src-exts
  - hpack
  - linear
  - megaparsec
  - mtl
  - pandoc
  - pointedlist
  - profunctors
  - recursion-schemes
  - show-prettyprint
  - singletons
  - split
  - taggy
  - taggy-lens
  - template-haskell
  - text
  - time
  - transformers
  - yaml

executables:
  aoc2018:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
    - optparse-applicative

tests:
  aoc2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018

benchmarks:
  aoc2018-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2018
