name:                aoc2018
version:             0.1.0.0
github:              "mstksg/advent-of-code-2018"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            "Advent of Code 2018 solutions and auto-runner"
category:            Web

description: |
    It's the Advent of Code 2018!

    This package contains Advent of 2018 solutions (spoilers!) and
    auto-runner.  Each challenge exists in its own module, and module headers
    will also include a brief synopsis and reflection.

ghc-options:
- -Wall
- -Wcompat
- -Wno-partial-type-signatures
- -Wredundant-constraints

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BlockArguments
- DataKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- KindSignatures
- LambdaCase
- MonadComprehensions
- MonoLocalBinds
- MultiParamTypeClasses
- MultiWayIf
- NumDecimals
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TransformListComp
- TupleSections
- TypeApplications
- TypeInType
- TypeOperators
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src
  dependencies:
  - advent-of-code-api >= 0.2.1
  - aeson
  - ansi-terminal
  - astar
  - bytestring
  - conduit
  - containers
  - criterion
  - curl
  - data-default
  - data-default-class
  - data-memocombinators
  - deepseq
  - directory
  - dlist
  - fgl
  - filepath
  - finite-typelits
  - foldl
  - free
  - free-algebras
  - groups
  - hashable
  - haskeline
  - haskell-names
  - haskell-src-exts
  - heredoc
  - hpack
  - lens
  - linear
  - megaparsec
  - microlens-th
  - mtl
  - nonempty-containers
  - pandoc
  - parallel
  - parsec
  - parser-combinators
  - pointedlist
  - primitive
  - profunctors
  - psqueues
  - pure-fft
  - recursion-schemes
  - semigroupoids
  - show-prettyprint
  - singletons
  - split
  - statistics
  - tagsoup
  - template-haskell
  - text
  - these
  - time
  - transformers
  - unordered-containers
  - vector
  - vector-sized
  - witherable
  - yaml

executables:
  aoc2018:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
    - optparse-applicative
    - microlens
    - containers
    - deepseq
    - lens
    - finite-typelits
    - ansi-terminal

tests:
  aoc2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
    - ansi-terminal

benchmarks:
  aoc2018-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2018
